# checks that pre-commit hooks pass before allowing to merge a PR

name: pre-commit
on:
  pull_request:
    branches: [main, master, staging, dev, feat/**, fix/**]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FOUNDRY_PROFILE: ${{ github.event_name == 'push' && 'ci' || 'pr' }}
  ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: bullfrogsec/bullfrog@7dee337d4575320b6d8cbe9a56d48d2fb765963a # v0.11.1
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@908c540300062bd5a7e473851cdb4282204cee09 # v1.9.1
        with:
          version: v1.8.1

      - name: Install pre-commit
        run: python -m pip install --upgrade pip==26.2.1 pre-commit==4.6.2

      - name: Run pre-commit
        run: pre-commit run --all-files --color always --show-diff-on-failure
        env:
          SKIP: forge-snapshots,generate-abis,generate-bindings-ts-wagmi,generate-bindings-go-go-ethereum,end-of-file-fixer,prettier
