name: test

on:
  pull_request:
    branches: [main, master, staging, dev, feat/**, fix/**]
  push:
    branches: [main, master, staging, dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FOUNDRY_PROFILE: ${{ github.event_name == 'push' && 'ci' || 'pr' }}
  ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}

jobs:
  forge-test:
    name: Foundry project
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: bullfrogsec/bullfrog@7dee337d4575320b6d8cbe9a56d48d2fb765963a # v0.11.1
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "1.27.1"
          cache-dependency-path: test/ffi/bls12381/go.sum

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@908c540300062bd5a7e473851cdb4282204cee09 # v1.9.1
        with:
          version: v1.8.5

      - name: Run Forge fmt check
        run: forge fmt --check

      - name: Run Forge tests
        run: forge test --isolate

      - name: Run Forge coverage
        run: |
          forge coverage --report lcov
        id: coverage
        env:
          COVERAGE: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
