name: test

on:
  push:

env:
  ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
